# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Everything 🚀
on:
  release:
    types: [published, prereleased]
  push:
    branches:
    - 'dev/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build and Deploy with Maven 🪶
      run: mvn -B deploy --file pom.xml
    - name: Build Javadocs 📚
      run: mvn -B javadoc:javadoc --file pom.xml

    - name: Stage
      run: |
        mkdir staging
        cp -r target/* staging
    - name: Deploy Javadocs 🚀
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./staging/site/apidocs
        keep_files: true
